AY2223S1-CS2113-F11-4/tp

- src/main/java/Patient.java
- src/main/java/PatientList.java
> Branch view patient list

- src/main/java/Patient.java
- src/main/java/Visit.java
Implemented add patient visit functionality, by creating
1. constructor function for Visit
2. getters and setters for getting details of visit
3. addVisit() method in patient class
> Add functions to add patient visit

- src/main/java/Visit.java
- src/main/java/VisitList.java
Added viewAll method in ViewList class, overrided toString method in Visit class, to retrieve visit information more efficiently.
> View all visits

- src/main/java/UI.java
> Add a skeletal UI class

- src/main/java/Patient.java
- src/main/java/PatientList.java
> Add functions to modify patient details given their ID and new details

- src/main/java/Messages.java
- src/main/java/OneDoc.java
- src/main/java/Prescription.java
- src/main/java/PrescriptionList.java
- src/test/java/PrescriptionListTest.java
- Add `viewAll` function for viewing prescription list
- Add JUnit Test for `viewAll` and `isEmpty` in PrescriptionList class
- Add a prescription list in `OneDoc`
> Add viewing all prescription records function

- src/main/java/Patient.java
- src/main/java/PatientList.java
> Add features to retrieve and print out the details of a patient given an ID

- src/main/java/Messages.java
- src/main/java/Prescription.java
- src/main/java/PrescriptionList.java
- src/main/java/Utils.java
- src/test/java/PrescriptionListTest.java
* Add edit prescription function
* Add prescription number when viewing all prescriptions
* Rearranged Prescription class's constructor's formal signature to match with the user command
* Add JUnit test for edit() function in PrescriptionList class
> Edit prescription : edit

- src/main/java/Prescription.java
- src/main/java/PrescriptionList.java
- src/main/java/Utils.java
- src/test/java/PrescriptionListTest.java
* Change time interval to String
* Change viewing format of Prescription
* Updated the JUnit tests
> Change timeInterval to String

- src/main/java/OneDoc.java
- src/main/java/OneDocException.java
- src/main/java/Parser.java
- src/main/java/PatientList.java
- Updated Parser to have a patientParser that collects user input and parses it with regex
- made minor edits to OneDocException to include a message
- made minor edits to Parser to pass in patientList
> Updated Parser to include a patientParser for handling user input

- src/main/java/OneDoc.java
- src/main/java/OneDocException.java
- src/main/java/Parser.java
- src/main/java/PatientList.java
- Updated Parser to have a visitParser that collects user input and parses it with regex
> Updated Parser to include a visitParser for handling user input

- src/main/java/Parser.java
- Added the option to view for Patient, Prescription, and Visits based on the command "viewall"
> Added a view option to each Parser

- src/main/java/Messages.java
- src/main/java/PatientList.java
- src/main/java/UI.java
- text-ui-test/EXPECTED.TXT
> Add messages to be printed out when patient menu is selected, patient is edited or added

- src/main/java/Parser.java
- src/main/java/UI.java
> Updated parser with new view visit functions

- src/main/java/Parser.java
- src/main/java/Patient.java
- src/main/java/UI.java
> Added parsing methods for prescription view methods, fixed some parsing

- diagrams/Sample.puml
Created a `diagrams` directory for all the `.puml` files
> Set up a diagrams directory

- docs/DeveloperGuide.md
- updated DG to include parser-specific explanation
> Updated DG to include parser-specific explanation

- src/main/java/Parser.java
- updated Parser to assert that the patientId doesn't contain any spaces when checking if it exists
> Updated Parser to contain asserts

- src/main/java/Parser.java
- changed an issue with using the incorrect variable name, which caused a bug for a few visit commands
> Changed variable names that were incorrect to fix bug

- src/test/java/ParserTest.java
- added junit tests for Parser
- checked each command functionality
- checked incorrect and correct inputs
> Created JUnit tests for the Parser for functionality and parsing

- docs/DeveloperGuide.md
- Updated parser section of dg
- Also added target user market and instructions on manual testing
> Updated parser section of developer guide as well as instructions and target user

- src/main/java/Parser.java
- src/main/java/PatientList.java
- updated both parser and patientList to ensure that new patients have unique ids compared to existing ones
> Updated parser and patientList to support unique IDs

- docs/UserGuide.md
- src/main/java/Prescription.java
- src/main/java/PrescriptionList.java
- src/main/java/UI.java
- src/test/java/PrescriptionListTest.java
* Reject adding prescription if it exists
* Reject editing prescription if it exists
* Add more tests in `PrescriptionListTest` for checking duplicate cases
* Refactor codes in `PrescriptionListTest`
* Add JavaDoc to some functions
* Minor changes in User Guide according to this functionality update
> Not allow duplicates of prescription

- docs/AboutUs.md
- docs/team/kaseykwok.md
* Added `kaseykwok.md` for my PPP draft
* Reformatted `AboutUs.md` and changed the links to portfolio
> Add PPP draft for kaseykwok and minor fix of AboutUs.md

- docs/team/riavora.md
Updated my team document to include my contributions
> [Ria] Updated ppp for contributions

- src/main/java/Parser.java
- src/main/java/PatientList.java
- Shortened a few methods and removed unnecessary comment
> Code Review for Ria

- src/main/java/Parser.java
- added a help message to the end of each error message and simplified error message
> Added help message to the end of each error message

- src/main/java/Parser.java
checks when the birth date is added or edited if the date is between  1922 to today and valid
checks day and month are valid
allows new visits to be in between 2012-292
> checks if birthdate, date, and time entered in input are valid

- docs/DeveloperGuide.md
- updated developer guide with parser information, non-functional requirements
- fixed minor spacing and information display errors
> [Developer Guide] Parser, Non-functional Requirements

- docs/team/riavora.md
- updated PPP with more detail to try and list all contributions
> [Ria] Updated ppp to list final contributions

- docs/AboutUs.md
Needed to add myself to the about us page lol
> [Ria] Added myself to the about us page

- docs/DeveloperGuide.md
- Added user testing examples for each command of patient, and a few commands of visit
> Added user testing examples for Patient and Visit

- src/main/java/Parser.java
> Add changes such that invalid dates and times can be detected in data files

- src/main/java/Parser.java
- updated to add java doc comments to Parser methods
> Updated to add java docs to public Parser methods

- src/main/java/Parser.java
- src/test/java/ParserTest.java
Visit date is checked against patient birthdate to ensure that visit happens after birthdate
> Updated visit to check against birth date
